spring.profiles.active: dev

#management:
#  server.port: 8081
#  endpoint.health.show-details: always
#  endpoints:
#    jmx:
#      exposure.include: '*'
#    web:
#      exposure.include: '*'

server.port: 8085
spring.application.name: micro-shop-service

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: micro1239.com
  cookieMaxAge: -1
  jwtSigningKey: dff51b86da1c7a730fcdeeb22320b426


# jackson
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  #quartz 任务调度框架
  quartz:
    job-store-type: jdbc #数据库方式
    #    startup-delay: 30
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: never #不初始化表结构
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler #调度器的实例名
            instanceId: AUTO #调度器编号自动生成
          jobStore:
            acquireTriggersWithinLock: true   #在锁定状态下获取触发器
            txIsolationLevelSerializable: true
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #我们仅为数据库制作了特定于数据库的代理
            useProperties: true #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
            tablePrefix: QRTZ_  #数据库表前缀
            misfireThreshold: 6000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
            clusterCheckinInterval: 5000 #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
            isClustered: true #打开群集功能,集群模式需要在多台服务器上做时间同步或者使用zookeeper去解决
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10 #最大线程个数
            threadPriority: 5 #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true
# MP 配置
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
# 日志
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    com.alibaba.nacos.client.naming: warn
    #org.springframework.security: info
    com.abc1236: debug
    #com.abc1236.ms.core.authentication: info
  file.path: logs/${spring.application.name}
# 数据源
#spring.datasource:
#  type: com.alibaba.druid.pool.DruidDataSource
#  url: jdbc:mysql://localhost:3306/linjiashop?useUnicode=true&characterEncoding=UTF8&useSSL=false
#  username: root
#  password: root
#  driverClassName: com.mysql.jdbc.Driver
##  driverClassName: com.mysql.cj.jdbc.Driver
#spring.redis:
#  host: localhost
#  password: 111111
#  port: 6379

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
  ServerListRefreshInterval: 3000
  okhttp.enabled: true
feign:
  okhttp.enabled: true
  client.config.default.loggerLevel: full


